server:
  port: 8051
---
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
        max-active: 8
        max-wait: 8
        min-idle: 0
        max-idle: 8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spbbase?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: lin123
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl