server:
  port: 8066
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://local.mysql.com:3306/spbbase?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: lin123
mybatis-plus:
  type-aliases-package: com.example.mybatisplus.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl